"""empty message

Revision ID: 2800446e4127
Revises: a02b2350842c
Create Date: 2018-09-19 02:36:50.661885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2800446e4127'
down_revision = 'a02b2350842c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.VARCHAR(length=32), nullable=True))
    op.drop_column('users', 'avatar_hash')
    # ### end Alembic commands ###
